ZDP-4306- Fix:  when the path ends with /*
zeotap/data-io pull request #14
Opened 2022-03-31 05:08 UTC by Akhilesh-Zeotap

2022-05-15 19:57 UTC, surya-lehar-zeotap approved these changes

2022-05-15 19:57 UTC, surya-lehar-zeotap commented
Squash the commits before merging

2022-05-20 10:32 UTC, surya-lehar-zeotap requested changes

2022-05-20 10:32 UTC, surya-lehar-zeotap commented on src/main/scala/com/zeotap/data/io/common/utils/CloudStorePathMetaGenerator.scala
> +    inputPathList.map(path => if(path.endsWith("/*")) new Path(path.substring(0,path.indexOf("/*"))) else new Path(path)).flatMap(path => {
This would give wrong results for the case where `/*` is in between the path

2022-08-22 05:54 UTC, WarisChutani approved these changes

2022-08-22 06:19 UTC, surya-lehar-zeotap approved these changes

2022-08-22 06:53 UTC, merged