ZP-7138: Bump spark & scala version for data-io
zeotap/data-io pull request #21
Opened 2022-12-05 15:47 UTC by KushagraTandon997

Jira - https://zeotap.atlassian.net/browse/ZP-7138

2022-12-05 15:50 UTC, anirudh-zeotap approved these changes

2022-12-05 15:52 UTC, surya-lehar-zeotap approved these changes

2022-12-08 11:17 UTC, surya-lehar-zeotap requested changes

2022-12-08 11:17 UTC, surya-lehar-zeotap commented on src/test/scala/com/zeotap/data/io/sink/beam/writer/JDBCBeamWriterTest.scala
> +    val actualDfSchema = checkSchemaEquality(actualDf.schema)
let's make minimal changes to the tests

2022-12-12 09:51 UTC, KushagraTandon997 commented on src/test/scala/com/zeotap/data/io/sink/beam/writer/JDBCBeamWriterTest.scala
> +    val actualDfSchema = checkSchemaEquality(actualDf.schema)
done

2022-12-12 09:56 UTC, surya-lehar-zeotap approved these changes

2022-12-12 09:59 UTC, merged